Build the about integration page
canonical-web-and-design/juju.is pull request #112
Opened 2020-09-15 20:41 UTC by anthonydillon

## QA
- Go to http://0.0.0.0:8041/about/integration
- Check the copy matches the [copy doc](https://docs.google.com/document/d/1xbMPHUB-vJ0G-TIozCarZXPDqhbQgf1EQb2lQlv6-3s/edit#)
- There are a number of illustrations requested in the copy doc.

Fixes https://github.com/canonical-web-and-design/juju.is/issues/96

2020-09-15 20:41 UTC, webteam-app commented
Demo starting at https://juju-is-112.demos.haus

2020-09-16 05:01 UTC, hatched requested changes

2020-09-16 05:01 UTC, hatched commented on templates/about/base.html
> +              <a class="p-side-navigation__link{% if request.path == '/about/integration' %} is-active{% endif %}" href="/about/integration">Reusable Operator Integration</a>
was this intended to be in another list item?

2020-09-16 21:50 UTC, anthonydillon commented
@hatched ready for another look.

2020-09-17 01:47 UTC, hatched approved these changes

2020-09-17 01:56 UTC, merged