Build the about operator-services page
canonical-web-and-design/juju.is pull request #119
Opened 2020-09-15 22:09 UTC by anthonydillon

## QA
- Go to http://0.0.0.0:8041/about/operator-services
- Check the content matches [the copy doc](https://docs.google.com/document/d/1_HS6kPV3jxSA0k9d-nr5PFu9V40Nv7d00N5tBwcPmG8/edit#)

Fixes https://github.com/canonical-web-and-design/juju.is/issues/103

2020-09-15 22:09 UTC, webteam-app commented
Demo starting at https://juju-is-119.demos.haus

2020-09-16 04:40 UTC, hatched requested changes

2020-09-16 04:40 UTC, hatched commented on templates/about/operator-services.html
> +App                   Version  Status   Scale  Charm                   Store       Rev  OS      Notes
Can you move this up to the previous line to avoid the empty space plz.

2020-09-16 21:38 UTC, anthonydillon commented
@hatched ready again

2020-09-17 01:11 UTC, hatched approved these changes

2020-09-17 01:12 UTC, merged