Build the homepage
canonical-web-and-design/juju.is pull request #125
Opened 2020-09-21 15:58 UTC by anthonydillon

Built the homepage from the [latest copy](https://docs.google.com/document/d/1vn6it-3px_KbplnajPlWPonU6W_xp4JdhE02kNQouZA/edit#).

## QA
- Open the demo
- Check the copy matches the copy doc

Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1403

2020-09-21 15:59 UTC, webteam-app commented
Demo starting at https://juju-is-125.demos.haus

2020-09-22 08:15 UTC, spencerbygraves commented
Thanks @anthonydillon. Can we use the light blue for the strips please, as on jaas.ai.

I would suggest some have the dark blue background, but I can't see from the doc that any strip is more important than another.

If we have illustrations, we could alternate their position left and right on the strips.

Thanks.

2020-09-22 09:13 UTC, spencerbygraves commented
@anthonydillon should "Windows | Mac | Linux" in the top section be links to the bottom section?

2020-09-22 10:40 UTC, anthonydillon commented
> Thanks @anthonydillon. Can we use the light blue for the strip backgrounds please, as on jaas.ai.

Done.

> I would suggest some have the dark blue background, but I can't see from the doc that any strip is more important than another.

The only dark one I have is the black strip but if you point me to an existing one I'll bring it over.

> If we have illustrations, we could alternate their position left and right on the strips.

Of course, left it basic for now.

2020-09-22 10:41 UTC, anthonydillon commented
> should "Windows | Mac | Linux" in the top section be links to the bottom section?

Not sure, maybe it should just be logos with links to the bottom like you said

2020-09-22 11:23 UTC, spencerbygraves commented
@anthonydillon in the bottom OLM section you've used a Linux logo, but it's an Ubuntu one in the doc.

2020-09-23 08:02 UTC, pmahnke requested changes
Comments inline

2020-09-23 08:02 UTC, pmahnke commented on templates/index.html
> +					<h2>Day 1, day 2, and beyond</h2>
remove the comma after 'day 2'

2020-09-23 08:02 UTC, pmahnke commented on templates/index.html
> +						Integrate heterogeneous environments transparently &mdash; connect services on the mainframe to applications on the cloud and in the data center.
centre not center

2020-09-23 09:32 UTC, spencerbygraves commented
@anthonydillon could you try this svg for the logos at the top please. Thanks.

https://assets.ubuntu.com/v1/9b2f65f0-juju.is-logos-banner.svg

2020-09-23 09:40 UTC, anthonydillon commented
> @anthonydillon could you try this svg for the logos at the top please. Thanks.

Done/

2020-09-23 10:21 UTC, anthonydillon commented
@spencerbygraves @pmahnke This one is ready for another look

2020-09-23 10:30 UTC, pmahnke requested changes
only the one comment

2020-09-23 10:30 UTC, pmahnke commented on templates/index.html
> +					<a href="/tour" class="p-link--inverted">Take the tour&nbsp;&rsaquo;</a>
remove the take the tour link from here and the nav

2020-09-23 10:30 UTC, pmahnke approved these changes
+1

2020-09-23 11:22 UTC, merged