Integrate cookie-policy v3.0.4
canonical-web-and-design/juju.is pull request #150
Opened 2020-10-07 15:49 UTC by anthonydillon

## Done
Integrate cookie-policy v3.0.4

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8041
- Check the cookie policy appears
- Check the manager opens and works
- Make a selection and the notification should disappear
- Scroll to the footer and click the Manage link in the footer
- See that manager appears again. 

## Issue / Card
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3270

2020-10-07 15:49 UTC, webteam-app commented
Demo starting at https://juju-is-150.demos.haus

2020-10-07 17:48 UTC, pmahnke requested changes
I think the global nav and cookies are in different directories. Also, can you change the GTM code to `GTM-K9KCMZ`

2020-10-07 17:48 UTC, pmahnke commented on package.json
> +    "copy-cookie-policy": "mkdir -p static/js/modules/cookie-policy && cp node_modules/@canonical/cookie-policy/build/js/cookie-policy.js static/js/modules/cookie-policy",
I think you are confusing `build` with `modules`

2020-10-08 07:09 UTC, pmahnke commented
oh, I thought this was for jaas.ai... sorry @anthonydillon

2020-10-08 14:45 UTC, anthonydillon commented
Superseded by #151

2020-10-08 14:45 UTC, closed without merging