Update GTM and add cookie policy
canonical-web-and-design/juju.is pull request #151
Opened 2020-10-07 17:45 UTC by pmahnke

## Done

- Update GTM and add cookie policy
- Removed the optimise code as it isn't being used

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8041
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See the cookie popup works, it in the footer and the GTM code is `GTM-K9KCMZ`

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/3269

2020-10-07 17:45 UTC, webteam-app commented
Demo starting at https://juju-is-151.demos.haus

2020-10-07 21:52 UTC, anthonydillon requested changes
Issue in the npm script. Why not push to the existing PR?

2020-10-07 21:52 UTC, anthonydillon commented on package.json
> +    "build-global-nav": "mkdir -p mkdir -p static/js/build/global-nav && cp node_modules/@canonical/global-nav/dist/global-nav.js static/js/build/global-nav",
You have double `mkdir -p` here

2020-10-08 07:07 UTC, pmahnke commented
@anthonydillon we can close this, I didn't see you had a PR, strange, I did check

2020-10-08 07:11 UTC, anthonydillon commented
No your PR has the GTM code updates which mine so it's fine.

2020-10-08 14:44 UTC, anthonydillon approved these changes
Nice catch on the clean command :+1:

2020-10-08 14:45 UTC, merged