Integrate LMA 2 docs in juju.is navigation
canonical-web-and-design/juju.is pull request #331
Opened 2021-09-27 16:37 UTC by mmanciop

## Done

Include the new LMA 2 Discourse topic as "Learn" and footer entry

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8041
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes something that Michele did not actually file as an issue because he likes PRs better :P

## Screenshots

[if relevant, include a screenshot]

2021-09-27 16:37 UTC, webteam-app commented
mmanciop is not a collaborator of the repo

2021-09-28 12:47 UTC, steverydz requested changes

2021-09-28 12:47 UTC, steverydz commented on templates/footer.html
> +          <a class="p-link--soft" href="https://juju.is/docs/lma2"><small>Observability (LMA 2)</small></a>
Can you make this a relative link?

2021-09-28 17:13 UTC, mmanciop commented on templates/footer.html
> +          <a class="p-link--soft" href="https://juju.is/docs/lma2"><small>Observability (LMA 2)</small></a>
Done

2021-09-30 08:03 UTC, steverydz approved these changes
LGTM 👍

2021-09-30 08:04 UTC, merged